### PR TITLE
Add `cov-srchtml` binary to output source-as-html with coverage info

### PR DESCRIPTION
**Pull request by richarddbarnett**
Output is a tree of html files containing source code, coloured & annotated with coverage info.
There's also a tree view for navigation.
Updated README & added screenshot.

Also 
* Fixed a couple of divide-by-zero errors
* Added a `ReleaseNoGtk` solution configuration which excludes building `cov-gtk`

### CODE REVIEW

**Comment by inorton** [comment]
This is absolutely brilliant work! Thank-you Richard!

**Comment by inorton** [comment]
@richarddbarnett would you mind squashing this into one commit on your fork? Then you appear in the source history (if I squash and merge it shows up as me) I want you to show up in the credits :)

**Comment by richarddbarnett** [comment]
Hi @inorton - thanks for merging this so quickly, sorry I didn't get around to squashing it for you (I assume you don't need that any more?)

**Comment by inorton** [comment]
I realised it still gives you credit in the commit list :) not needed now

**Pull request merged**
